### ISSUE TITLE
Turn on GitHub pages deployment

### ISSUE THREAD

**Issue by abhro** [JuliaAstro/AstroAngles.jl#8]
The package has a fully functioning docs site, and it would be worthwhile to serve from the gh-pages branch for an easily accessible docs site.

There is a copy on base juliaastro.org, but that also includes a lot of other packages and tightly integrates all astro-related packages (or at least their docs). See issue https://github.com/JuliaAstro/JuliaAstro.github.io/issues/30

**Comment by giordano** [comment]
Done: https://juliaastro.org/AstroAngles.jl/dev/

**Comment by abhro** [comment]
Thank you!!
